apiVersion: v1
kind: Service
metadata:
  name: servicehello
  labels:
    app: {{ template "hello.name" . }}
    chart: {{ template "hello.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ template "hello.name" . }}
    release: {{ .Release.Name }}
